input_namespace: null
output_namespace: utility_linklocalfolder
utility_linklocalfolder:
  name: (Utility) LinkLocalFolder
  type: module
  snakefile:
    function: github
    args:
    - kraemer-lab/vneyard
    kwargs:
      path: workflows/Utility/sources/LinkLocalFolder/workflow/Snakefile
      commit: 756a388c95513710e850bb3f20d0a10872753a40
  parameter_map: []
  config:
    input_namespace: null
    output_namespace: utility_linklocalfolder
    params:
      folder: <Full path to local file>
